version: "3.9"
networks:
  my-network:
    driver: bridge
services:
  my-generator:
    build: ./generator
    # Do we need links?
    links:
      - my-kafka
    command: bash -c "python producer.py"
    # https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "9000:9000"
    volumes:
      - ./generator/code:/code
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - my-network
    image: vandosik/generator:latest
    depends_on:
     - my-kafka
  my-kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://my-kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@my-kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=L0ZEQh1yTbGhNNUE7-6wSQ
    volumes:
      - ./kafka:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - my-network
  my-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=my-kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - my-network
    depends_on:
     - my-kafka
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
  my-cassandra:
    image: cassandra:latest
    volumes:
      - ./cassandra:/cassandra
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 3000M
        reservations:
          cpus: '0.5'
          memory: 2000M
  # my-client:
  #   build: ./client
  #   links:
  #     - my-kafka
  #   command: bash -c "python listener.py"
  #   #https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   volumes:
  #     - ./client/code:/code
  #   networks:
  #     - my-network
  #   image: vandosik/client:latest
  #   depends_on:
  #    - my-kafka
  #    - my-cassandra
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 60s
  my-spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    networks:
      - my-network
  my-spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://my-spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - my-network
    deploy:
      mode: replicated
      replicas: 2
  my-spark-client:
    build: ./spark
    image: vandosik/spark-client:latest
    command: bash -c /code/start_listeners.sh
    networks:
      - my-network
    volumes:
      - ./spark/code:/code
    links:
      - my-spark-master
      - my-kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
  jupyter-notebook:
    ports:
      - '8888:8888'
    image: jupyter/minimal-notebook:latest
    networks:
      - my-network
    links:
      - my-spark-master
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M


