apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: my-grafana
  name: my-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: my-grafana
    spec:
      containers:
        - env:
            - name: GF_LOG_LEVEL
              value: debug
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: hadesarchitect-cassandra-datasource
          image: vandosik/grafana:latest
          name: my-grafana
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: my-grafana-claim0
      restartPolicy: Always
      volumes:
        - name: my-grafana-claim0
          persistentVolumeClaim:
            claimName: my-grafana-claim0
status: {}
