apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: my-spark-worker
  name: my-spark-worker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8082"
      port: 8082
      targetPort: 8081
    - name: "8083"
      port: 8083
      targetPort: 8081
    - name: "8084"
      port: 8084
      targetPort: 8081
    - name: "8085"
      port: 8085
      targetPort: 8081
    - name: "8086"
      port: 8086
      targetPort: 8081
    - name: "8087"
      port: 8087
      targetPort: 8081
    - name: "8088"
      port: 8088
      targetPort: 8081
    - name: "8089"
      port: 8089
      targetPort: 8081
    - name: "8090"
      port: 8090
      targetPort: 8081
    - name: 8081-tcp
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: my-spark-worker
status:
  loadBalancer: {}
