apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: my-kafka
  name: my-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-kafka
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: my-kafka
    spec:
      containers:
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://my-kafka:9092
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 1@my-kafka:9093
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: L0ZEQh1yTbGhNNUE7-6wSQ
          image: bitnami/kafka:latest
          name: my-kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: my-kafka-claim0
      restartPolicy: Always
      volumes:
        - name: my-kafka-claim0
          persistentVolumeClaim:
            claimName: my-kafka-claim0
status: {}
