apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: my-kafka-ui
  name: my-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-kafka-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: my-kafka-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: my-kafka-0.my-kafka-headless.default.svc.cluster.local:9092
          image: provectuslabs/kafka-ui:v0.4.0
          name: my-kafka-ui
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 200m
              memory: "268435456"
      restartPolicy: Always
status: {}
