apiVersion: v1
kind: ConfigMap
metadata:
  name: sparkCM
data:
  KAFKA_BOOTSTRAP_SERVERS: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092
  CASSANDRA_NODES: my-release-cassandra.default.svc.cluster.local
  CASSANDRA_PORT: 9042
  CASSANDRA_USER: admin
  CASSANDRA_PASSWORD: password